DROP INDEX INDEX_REVIEWS_YELP_USER;

DROP INDEX INDEX_REVIEWS_BUSINESS;

DROP TABLE REVIEWS;
DROP TABLE CHECKIN;
DROP TABLE NEIGHBORHOODS;
DROP TABLE BUSINESS_ATTRIBUTES;
DROP TABLE MAIN_CATEGORIES;
DROP TABLE SUB_CATEGORIES;
DROP TABLE BUSINESS_HOURS;
DROP TABLE BUSINESS;
drop table ELITE;
drop table FRIENDS;
drop table YELP_USER;
